#cloud-config
packages:
  - openssh
runcmd:
  - |
    if ! grep -qi '^ *AllowAgentForwarding' /etc/ssh/sshd_config; then
      echo 'AllowAgentForwarding yes' >> /etc/ssh/sshd_config
    fi
  - systemctl daemon-reload
  - systemctl enable --now sshd