#cloud-config
users:
  - name: zyrakq
    gecos: Zyrakq
    sudo: ALL=(ALL) NOPASSWD:ALL
    primary_group: zyrakq
    groups: [wheel, users, zyrakq]
    homedir: /home/zyrakq
    groups: wheel
    shell: /bin/zsh
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMGr4Gmaz9+pF7lGS/0SFIah6vgukPbm7PcRF55G4VIp zyrakq@tantal
hostname: tantal

write_files:
# welcome
  - path: /etc/motd
    content: |
      Arch in Incus + Cloud-init + SSH ready!

package_upgrade: true
packages:
  - base-devel
  - git
  - kitty-terminfo
  - htop
  - nano
runcmd:
  - timedatectl set-ntp true